import { useCallback, useEffect, useMemo, useState } from 'react'
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Cell } from 'recharts'

import PageHeader from '../components/PageHeader'
import StatTile from '../components/StatTile'
import GanttChart from '../components/GanttChart'
import { LoadingPanel, EmptyPanel, ErrorPanel } from '../components/LoadingState'
import { useToast } from '../hooks/useToast'
import { generateSchedule, getCurrentSchedule } from '../api/client'

const SHIFT_WORKING_MINS = 480

export default function ScheduleView() {
  const [assignments, setAssignments] = useState(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState(null)
  const [lastResult, setLastResult] = useState(null)
  const toast = useToast()

  const load = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const data = await getCurrentSchedule()
      setAssignments(data.assignments || [])
    } catch (e) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    load()
  }, [load])

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const result = await generateSchedule()
      setLastResult(result)
      if (result.status === 'OPTIMAL' || result.status === 'FEASIBLE') {
        toast.success(
          `Schedule generated (${result.status}) — ${result.assignments?.length ?? 0} assignments`,
        )
        await load()
      } else {
        toast.error(`Solver returned ${result.status}. No schedule written.`)
      }
    } catch (e) {
      toast.error(`Generation failed: ${e.message}`)
    } finally {
      setGenerating(false)
    }
  }

  // ── Derived KPIs ──────────────────────────────────────────────────────
  const stats = useMemo(() => {
    if (!assignments || assignments.length === 0) return null
    const orders = new Set(assignments.map((a) => a.production_order))
    const machines = new Set(assignments.map((a) => a.machine_name))
    const dates = new Set(assignments.map((a) => a.scheduled_date))

    // Average utilization per machine (consumed minutes / (slots × 480))
    const byMachineSlot = {}
    for (const a of assignments) {
      const slotKey = `${a.machine_name}|${a.scheduled_date}|${a.shift}`
      byMachineSlot[slotKey] = (byMachineSlot[slotKey] || 0) + (a.end_offset_min - a.start_offset_min)
    }
    const utilValues = Object.values(byMachineSlot).map((m) => Math.min(100, (m / SHIFT_WORKING_MINS) * 100))
    const avgUtil = utilValues.length
      ? Math.round(utilValues.reduce((s, v) => s + v, 0) / utilValues.length)
      : 0

    // Per-machine utilization for bar chart
    const machineConsumed = {}
    const machineSlotCount = {}
    for (const a of assignments) {
      machineConsumed[a.machine_name] =
        (machineConsumed[a.machine_name] || 0) + (a.end_offset_min - a.start_offset_min)
    }
    for (const key of Object.keys(byMachineSlot)) {
      const [m] = key.split('|')
      machineSlotCount[m] = (machineSlotCount[m] || 0) + 1
    }
    const machineUtilization = Array.from(machines)
      .map((m) => ({
        machine: m,
        utilization: machineSlotCount[m]
          ? Math.round(Math.min(100, (machineConsumed[m] / (machineSlotCount[m] * SHIFT_WORKING_MINS)) * 100))
          : 0,
      }))
      .sort((a, b) => b.utilization - a.utilization)

    return {
      orderCount: orders.size,
      machineCount: machines.size,
      dateCount: dates.size,
      avgUtil,
      machineUtilization,
    }
  }, [assignments])

  return (
    <div>
      <PageHeader
        title="Schedule"
        subtitle="Shift-level Gantt across all machines · generated by Engine 1 (CP-SAT)"
        actions={
          <button className="btn-primary" onClick={handleGenerate} disabled={generating}>
            {generating ? 'Generating…' : 'Generate Schedule'}
          </button>
        }
      />

      <div className="p-6 space-y-6">
        {lastResult && (
          <div className="card px-4 py-3 flex items-center gap-4 text-sm">
            <span className="font-medium text-slate-700">Last run:</span>
            <StatusPill status={lastResult.status} />
            {lastResult.objective_value != null && (
              <span className="text-slate-500">
                Objective: <span className="font-mono">{lastResult.objective_value.toFixed(1)}</span>
              </span>
            )}
            <span className="text-slate-400 text-xs">Run ID: {lastResult.run_id}</span>
          </div>
        )}

        {loading && <LoadingPanel label="Loading current schedule…" />}
        {!loading && error && <ErrorPanel message={error} onRetry={load} />}

        {!loading && !error && (!assignments || assignments.length === 0) && (
          <EmptyPanel
            title="No schedule generated yet"
            hint="Click 'Generate Schedule' to run Engine 1 against the current WIP orders and machine capacity."
          />
        )}

        {!loading && !error && assignments && assignments.length > 0 && stats && (
          <>
            {/* KPI row — clear at a glance */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <StatTile label="Orders scheduled" value={stats.orderCount} tone="brand" />
              <StatTile label="Machines in use" value={stats.machineCount} />
              <StatTile label="Horizon (days)" value={stats.dateCount} />
              <StatTile
                label="Avg. shift utilization"
                value={`${stats.avgUtil}%`}
                tone={stats.avgUtil >= 85 ? 'breach' : stats.avgUtil >= 50 ? 'brand' : 'neutral'}
              />
            </div>

            {/* Utilization bar chart */}
            <div className="card p-4">
              <h3 className="text-sm font-semibold text-slate-700 mb-3">Utilization by Machine</h3>
              <ResponsiveContainer width="100%" height={Math.max(160, stats.machineUtilization.length * 32)}>
                <BarChart data={stats.machineUtilization} layout="vertical" margin={{ left: 8, right: 24 }}>
                  <CartesianGrid strokeDasharray="3 3" horizontal={false} />
                  <XAxis type="number" domain={[0, 100]} unit="%" tick={{ fontSize: 11 }} />
                  <YAxis type="category" dataKey="machine" width={90} tick={{ fontSize: 11 }} />
                  <Tooltip formatter={(v) => [`${v}%`, 'Utilization']} />
                  <Bar dataKey="utilization" radius={[0, 4, 4, 0]} barSize={16}>
                    {stats.machineUtilization.map((entry, i) => (
                      <Cell
                        key={i}
                        fill={
                          entry.utilization >= 85
                            ? '#dc2626'
                            : entry.utilization >= 50
                              ? '#2563eb'
                              : '#94a3b8'
                        }
                      />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Gantt chart */}
            <div className="card p-4">
              <h3 className="text-sm font-semibold text-slate-700 mb-3">Gantt — Machine × Shift</h3>
              <GanttChart assignments={assignments} />
            </div>
          </>
        )}
      </div>
    </div>
  )
}

function StatusPill({ status }) {
  const styles = {
    OPTIMAL: 'bg-risk-safeBg text-risk-safe',
    FEASIBLE: 'bg-brand-100 text-brand-700',
    INFEASIBLE: 'bg-risk-breachBg text-risk-breach',
    MODEL_INVALID: 'bg-risk-breachBg text-risk-breach',
    UNKNOWN: 'bg-slate-100 text-slate-500',
  }
  return <span className={`badge ${styles[status] || styles.UNKNOWN}`}>{status}</span>
}
